messages:
  no-permission: "&cNo permission."
  must-be-player: "&cOnly players can run this command"
  incorrect-usage: "&cIncorrect usage: %usage%"
  unknown-sub-command: "&cUnknown sub-command"
command-messages:
  reset:
    reset-message: "&aReset quests tables"
  cancel:
    not-in-quest: "&cYou have no quest in progress"
    cancelled: "&aCancelled quest"
database:
  host: localhost
  port: 3306
  username: username
  password: password
  name: name
quest-creation-messages:
  quit-quest-creation: "&cFailed to create quest"
  input-name: "&aInput quest name"
  input-description: "&aInput quest description"
  finished-creating-quest: "&aFinished creating quest!"
  select-type: "&aSelect objective"
  set-xp: "&aSelect the amount of levels"
  set-coins: "&aSelect the amount of coins"
  set-name: "&aSet name to %value%"
  set-description: "&aSet description to %value%"
  set-type: "&aSet type to %value%"
  place-items: "&aPlace items in inventory"
  added-commands: "&aAdded %value% commands"
  added-items: "&aAdded %value% items"
  break-blocks-inventory: "&aPlace the blocks you want them to break"
  place-blocks-inventory: "&aPlace the blocks you want them to place"
  place-items-inventory: "&aPlace the items you want them to obtain"
  input-entity: "&aInput entity name"
  input-permission: "&aInput permission"
  input-advancement-name: "&aInput advancement name"
  invalid-entity: "&cInvalid entity"
  invalid-advancement: "&cInvalid advancement"
quest:
  quest-start: "&aStarted %quest_name% quest!"
  already-in-quest: "&cYou are already in a quest!"
  completed-quest: "&6Completed %quest_name% quest!"
confirm-gui:
  cancel-message: "&aCancelled"
player-join-message: # Variables: %quest_name%, %quest_progress%, %quest_progress_needed%, %player_name%
  - "&aWelcome %player_name%"
  - "&aYou are %quest_progress%/%quest_progress_needed% on your %quest_name% quest"