name: Quests
main: dev.blackgate.questsystem.QuestSystem
version: 1
author: JuicySeals
api-version: 1.20
softdepend: [ PlaceholderAPI ]
commands:
  quests:
    usage: /quests <subcommand>
    description: The base command for quests. Will show help if no subcommand specified.