name: Quests
main: dev.blackgate.questsystem.QuestSystem
version: 1
author: JuicySeals
api-version: 1.20
commands:
  quest:
    usage: /quest <subcommand>
    description: The base command for quests. Will show help if no subcommand specified.